export * from './modules/user'
export * from './modules/medal'
export * from './modules/order'
export * from './modules/classIn'
export * from './modules/persondetail'
export * from './modules/classtable'
export * from './modules/paper'
export * from './modules/preExam'
export * from './modules/examOrder'
export * from './modules/newSalary'
export * from './modules/newTrain'
export * from './modules/smallQuestionBank'
export * from './modules/table'
export { default as request } from './request'
export { default as hatchRequest } from './hatch-request'
export * from './config'
